const data=[
    {    
   id:1,
   name:"Tobey Maguire",
   birthday:"Jun 27, 1975",
   film_name:"Peter Parker (Spider-Man)",
   img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/spider-man_main-1280x720.jpg?fit=bounds&width=1280&height=720&dpr=2",
   appearance:"Spider Man",
   category:"MCU",
},
{  
        id:2,
        name:"Robert Downey Jr",
        birthday:"Apr 4, 1965",
        film_name:"Tony Stark (Iron Man)",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/the-evolution-of-iron-man-in-the-mcu.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Tony Stark / Iron Man ",
        category:"MCU" , 
},
{
   
        id:3,
        name:"Scarlett Johansson",
        birthday:"Nov 22, 1984",
        film_name:"Natasha Romanoff (Black Widow)",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/ocA7mZJmT97HzvesMjkXKA.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Black Widow",
        category:"MCU",
},
{
  
        id:4,
        name:"Chadwick Boseman",
        birthday:"Nov 29, 1976",
        film_name:"King T'Challa (Black Panther)",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/Chadwick-Boseman-as-Black-Panther-Featured-Image.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Black Panther",
        category:"MCU",
},
{   
        id:5,
        name:"Paul Rudd",
        birthday:"Apr 6, 1969 ",
        film_name:"Scott Lang (Ant-Man)",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/antman-falcon.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Ant-Man and the Wasp",
        category:"MCU",
},
{ 
        id:6,
        name:"Samuel L. Jackson",
        birthday:"Dec 21, 1948",
        film_name:"Nick Fury",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/1486123002-nick-fury-avengers.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Iron Man,Avangers",
        category:"MCU",
},
{
        id:7,
        name:"Zoe Saldaña",
        birthday:"Jun 19, 1978 ",
        film_name:"Gamora",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2021/02/gamora.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Gamora",
        category:"MCU",
    
},
{  
        id:8,
        name:"Jeremy Lee Renner ",
        birthday:"Jan 7, 1971",
        film_name:"Clint Barton (Hawkeye)",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/avengers-4-what-hawkeyes-ronin-costume-reveals-about-the-sta_qn9z.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"The Avengers,Clint Barton / Hawkeye ",
        category:"MCU",
},
{
      
        id:9,
        name:"Letitia Wright",
        birthday:"Oct 31, 1993",
        film_name:"Shuri",
        img:"https://oyster.ignimgs.com/wordpress/stg.ign.com/2020/12/avengers-infinity-war-shuri-1103732-1280x0.jpg?fit=bounds&width=1280&height=720&dpr=2",
        appearance:"Black Panther: Wakanda Forever",
        category:"MCU",
},
{
  
        id:10,
        name:"Ben Affleck",
        birthday:"Aug 15, 1972",
        film_name:"Batman",
        img:"https://th.bing.com/th/id/R.37ebcc3c9c5117e5549cc41d823e3da3?rik=2m5e68i3OgcbZA&riu=http%3a%2f%2frevistaplaylist.com%2fwp-content%2fuploads%2f2020%2f08%2fthe-batman-thumb-2-1598144709554.jpg&ehk=0bYdhjeq5FHCZT6RKBV8R2zhaP6BnBCHXzVPgsPVLy4%3d&risl=&pid=ImgRaw&r=1",
        appearance:"Batman/Bruce Wayne",
        category:"MCU",
},
{  
        id:11,
        name:"Gal Gadot",
        birthday:"Apr 30, 1985",
        film_name:"Wonder Women",
        img:"https://th.bing.com/th/id/OIP.SrbC6c23f6y7NRJwNtdDswHaEo?pid=ImgDet&rs=1",
        appearance:"Wonder Woman",
        category:"MCU",
},
{  
        id:12,
        name:"Hugh Jackman",
        birthday:"Oct 12, 1968",
        film_name:"Wolverine (Logan)",
        img:"https://wallpaperaccess.com/full/1191402.jpg",
        appearance:"X-Men film series",
        category:"MCU",
}
]
export default data